version: '3.3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - certs:/etc/nginx/certs:ro
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - vhostd:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro

  www:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=guruh.co,www.guruh.co
      - LETSENCRYPT_HOST=guruh.co,www.guruh.co
      - LETSENCRYPT_EMAIL=cahupa99@gmail.com


  backend:
    build: ../GURUH/.
    restart: always
    expose:
      - 3000

  api:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ../GURUH/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=api.guruh.co
      - LETSENCRYPT_HOST=api.guruh.co
      - LETSENCRYPT_EMAIL=business@guruh.co

  n8n-nginx:
    image: nginx
    restart: always
    expose:
      - "80"
    volumes:
      - ../n8n/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=n8n.guruh.co
      - LETSENCRYPT_HOST=n8n.guruh.co
      - LETSENCRYPT_EMAIL=business@guruh.co

  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    expose:
      - 5678
    environment:
      - N8N_HOST=n8n.guruh.co
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.guruh.co/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  n8n_data:
  certs:
  html:
  vhostd:
